import { Collapse } from 'bootstrap'
import {authModalInstance} from '../../components/modals/auth-modal/auth-modal'
import {regModalInstance} from '../../components/modals/registration-modal/registration-modal'
import '../../components/filter/filter'
import '../../components/filter-mobile/filter-mobile'
